language: cpp

os:
  - linux
  - osx

dist: bionic
osx_image: xcode12u

addons:
  apt:
    update: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost ccache pkg-config lilv suil; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y python git build-essential pkg-config libboost-signals-dev libfreetype6-dev libx11-dev libxext-dev libxrandr-dev libxcomposite-dev libxinerama-dev libxcursor-dev libjack-dev libasound2-dev lv2-dev liblilv-dev libsuil-dev ladspa-sdk libcurl4-openssl-dev libgtk2.0-dev; fi

script: python waf configure clean build
